#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" pykwalify - script entry point """

__author__ = 'Grokzen <grokzen@gmail.com>'

import os
import sys

# Check minimum version of Python
if sys.version_info < (2, 7, 0):
    sys.stderr.write("WARNING: pykwalify: It is recommended to run pykwalify on python version 2.7.x or later...\n\n")

# Add current path so python can find pykwalify folder if it is not installed yet
(prefix, bindir) = os.path.split(os.path.dirname(os.path.abspath(sys.argv[0])))
sys.path.append(prefix)

import pykwalify.cli

if __name__ == "__main__":
    pykwalify.cli.run(pykwalify.cli.parse_cli())
